repos:
  - repo: local
    hooks:
      - id: type-check
        name: Try to type-check
        language: system
        entry: pnpm type-check
        stages: [commit]
        pass_filenames: false

      - id: build
        name: Try to build
        language: system
        entry: pnpm build
        stages: [commit]
        pass_filenames: false

      - id: lint
        name: Try to lint
        language: system
        entry: pnpm lint
        stages: [commit]
        pass_filenames: false

      - id: format
        name: Try to format
        language: system
        entry: pnpm format
        stages: [commit]
        pass_filenames: false
